title: Derby City Watch
name: Derby City Watch Feed
timezone: America/New_York
description: Public safety updates processed from scanner traffic in Louisville, Kentucky.
# Use a mobile-friendly theme supported by GitHub Pages
remote_theme: jekyll/minima #jekyll-theme-cayman & pages-themes/minimal
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 500 # Number of posts to show per page
paginate_path: "/page/:num/"

# Configure navigation menu
header_pages:
  - index.md
  - digest.md
  - about.md
