title: Derby City Watch Real-Time Feed
timezone: America/Kentucky/Louisville
description: Public safety updates processed from scanner traffic.
# Use a mobile-friendly theme supported by GitHub Pages
remote_theme: jekyll-theme-cayman #pages-themes/minimal
markdown: kramdown
plugins:
  - jekyll-remote-theme
# --- Pagination Settings ---
paginate: 20           # How many posts to show per page
paginate_path: "/page:num/" # The URL structure for subsequent pages